### PR TITLE
Close button now rounded

### PR DESCRIPTION
**Pull request by GFerreiroS**

### CODE REVIEW

**Comment by SarwinR** [comment]
Its good, but only the close button for the folder-creation-modal was fixed. There are 2 more close buttons: folder-setting-modal and class-setting-modal. Can you fix it?

**Comment by GFerreiroS** [comment]
Oh yeah sorry didnt see those :D

**Comment by GFerreiroS** [comment]
Now it should be all rounded

**Comment by SarwinR** [comment]
Nice Work 👍

**Pull request merged**
